package cz.bliksoft.meshcore.frames;

import cz.bliksoft.meshcore.frames.FrameConstants.CommandFrameType;
import cz.bliksoft.meshcore.frames.FrameConstants.ResponseFrameType;

/**
 * frame type generated by the application
 */
public abstract class CommandFrame extends Frame {

	public static final byte[] EXPECTED_OK = new byte[] { ResponseFrameType.RESP_OK.code() };
	public static final byte[] EXPECTED_OK_ERR = new byte[] { ResponseFrameType.RESP_OK.code(),
			ResponseFrameType.RESP_ERR.code() };
	public static final byte[] EXPECTED_SENT = new byte[] { ResponseFrameType.RESP_SENT.code(),
			ResponseFrameType.RESP_ERR.code() };;

	@Override
	public boolean is(FrameType type) {
		return FrameType.COMMAND.equals(type);
	}

	public abstract CommandFrameType getFrameType();

	public boolean is(CommandFrameType type) {
		return getFrameType().equals(type);
	}

	public byte[] expectedResponses() {
		return EXPECTED_OK_ERR;
	}

	@Override
	public byte getTypeCode() {
		return getFrameType().code();
	}

	@Override
	public String toString() {
		return getFrameType().toString();
	}

	/**
	 * Returns the expected async content-response type, or {@code null} if this
	 * command has no two-stage response.
	 */
	public ResponseFrameType getExpectedResponseFrameType() {
		return null;
	}

	/**
	 * key value to listen for to get response frame if supported. Can store
	 * response frame for timeout calculation.
	 *
	 * @return null if not supported or not expecting a response. callResult will be
	 *         returned immediately in that case with no registration of listener.
	 */
	public String getResultKey(ResponseFrame callResult) {
		return null;
	}

	/**
	 * Returns a suggested timeout in milliseconds for the async content response,
	 * or {@code null} to use the caller-supplied default.
	 */
	public Long getExpectedResponseTimeout() {
		return null;
	}
}
